config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :update, :member, :makemember]
  # devise_scope :users do
  # get 'users/member/:id', to: 'users#member'
  get 'member/new/:id', to: 'users#member'
  patch  'member/become/:id', to: 'users#makemember'
  # end
  # get 'users/:id', to: 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  # resources "cases"
  resources :cases do
    resources :comments
  end

  resources "members"
  get 'closes/:id', to: 'cases#close_case'
  get 'verify/:id', to: 'cases#verify_case'
  get 'events', to: 'home#event'

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
    before_action :authenticate_user!, only: [:new]
    def index
      @cases = current_user.cases
    end

    def show
        @case = Case.find(params[:id])
    end

    def new
        @user = User.find(current_user.id)
        @case = @user.cases.new
    end

    def create
        @user = User.find(current_user.id)
        @case = @user.cases.create(case_params)
        if @case.save
            redirect_to root_path
          else
            render :new, status: :unprocessable_entity
          end
    end

    def edit
      @user = User.find(current_user.id)
      @case = @user.cases.find(params[:id])
    end

    def update
      @case = Case.find(params[:id])

      if @case.update(case_params)
        redirect_to case_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @case = Case.find(params[:id])
      @case.destroy
  
      redirect_to root_path, status: :see_other
    end

    def close_case
      Case.close_case(params[:id])
      redirect_to cases_path
    end

    def verify_case
      Case.verify_case(params[:id])
      redirect_to root_path
    end
    private
    def case_params
      params.require(:case).permit(:title, :type, :location, :description, :up_votes, :deadline)
    end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/_form.html.erb
<%= form_with model: @case do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @case.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :type %><br>
    <%= form.select :desired_attribute, ['Medical', 'Education', 'Marriage']%>
    <% @case.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %><br>
    <% @case.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :deadline %><br>
    <%= form.date_field :deadline, :value => Date.current%><br>
    <% @case.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @case.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    
  <%= form.hidden_field :up_votes, :value => 0 %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<h1>Update Case</h1>

<%= render 'form'%>

app/views/cases/index.html.erb
<h1>My Cases</h1>
<h3>Open Cases</h3>
<table class="table">
  <thead>
    <tr>
      <%# <th scope="col">#</th> %>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Close</th>
    </tr>
  </thead>
  <tbody>
  <% @cases.each do |c| %>
  <% if not c.is_closed%>
    <tr>
      <%# <th scope="row">1</th> %>
      <td><a href="/cases/<%= c.id %>"><%= c.title %></a></td>
      <td><%= c.description %></td>
      <td><a href="/closes/<%= c.id %>"><button class="btn btn-sm btn-outline-dark">close</button></a></td>
    </tr>
<%end%>
    <%end%>
  </tbody>
</table>

<h3>Closed Cases</h3>
<table class="table">
  <thead>
    <tr>
      <%# <th scope="col">#</th> %>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Deadline</th>

    </tr>
  </thead>
  <tbody>
  <% @cases.each do |c| %>
  <% if c.is_closed%>
    <tr>
      <%# <th scope="row">1</th> %>
      <td><a href="/cases/<%= c.id %>"><%= c.title %></td>
      <td><%= c.description %></td>
      <td><%= c.deadline%></td>
    </tr>
<%end%>
    <%end%>
  </tbody>
</table>

app/views/cases/new.html.erb
<h1>New Case</h1>

<%= render 'form'%>

app/views/cases/show.html.erb
<h2>Title: <%= @case.title %></h2>
<%if @case.is_verified%>
<h5>Verified Case</h5>
<%end%>
<h6>Description: </h6>
<p><%= @case.description %></p>

<h6>Deadline: </h6>
<p><%= @case.deadline %></p>

<% if user_signed_in? %>
        <ul>
        <% if  @case.user_id == current_user.id %>
            <%= link_to "Edit", edit_case_path(@case), class: "btn btn-sm btn-outline-dark"%>
            <%= link_to "Destroy", case_path(@case), data: {
                                turbo_method: :delete}, class: "btn btn-sm btn-outline-dark" %>
        <%end%>

        <% if current_user.is_member and not @case.is_verified%>
            <a href="/verify/<%= @case.id %>">verify</a>
        <%end%>
        </ul>
        
        <h5>Comments</h5>
        <% @case.comments.each do |comment| %>
        <p>
            <strong>Commenter:</strong>
            <%= comment.commenter %>
        </p>

        <p>
            <strong>Comment:</strong>
            <%= comment.body %>
        </p>
        <%if comment.user_id == current_user.id%>
        <%# <p>Delete</p> %>
        <%= link_to "Delete Comment Comment", [comment.case, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: 'btn btn-outline-dark btn-sm' %>
        <% end %>
        <% end %>
        
        
        <h5>Add a comment:</h5>
        <%= form_with model: [ @case, @case.comments.build ] do |form| %>
        <p>
            <%= form.label :commenter %><br>
            <%
            user_name = current_user.firstname
            if current_user.lastname
                user_name = user_name + " " + current_user.lastname
            end
            %>
            <%= form.text_field :commenter, :value => user_name, :readonly => true  %>
        </p>
        <p>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
        </p>
        <%= form.hidden_field :user_id, :value => current_user.id %>

        <p>
            <%= form.submit class: 'btn btn-outline-dark btn-sm' %>
        </p>
        <% end %>
    
<% end %>