config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :update, :member, :makemember]
  # devise_scope :users do
  # get 'users/member/:id', to: 'users#member'
  get 'member/new/:id', to: 'users#member'
  patch  'member/become/:id', to: 'users#makemember'
  # end
  # get 'users/:id', to: 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  # resources "cases"
  resources :cases do
    resources :comments
  end

  resources "members"
  get 'closes/:id', to: 'cases#close_case'
  get 'verify/:id', to: 'cases#verify_case'
  get 'events', to: 'home#event'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @cases = Case.all
    end

    def event
        # redirect_to events_path
        render "home/event"
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
      <%= image_tag("kaar-e-kamal-1.png", :alt => "rss feed", style: 'height:auto;width:100px;') %>
      
      </a>
      <%# <img src="/images/kaar-e-kamal-1.png" alt="rss feed" /> %>
    </div>
    
      <ul class="nav navbar-nav ">

        <% if user_signed_in? %>
        <li><%= link_to 'Create Case', new_case_path , class: "nav-link"  %></li>
        <li><%= link_to 'My Cases', cases_path , class: "nav-link"  %></li>
      
        <% if not current_user.is_member%>
        <li><a href="/member/new/<%= current_user.id %>", class= "nav-link"><%= "Become Member" %></a><li>
        <%# <li><%= link_to 'Become Member', member_new_path , class: "nav-link"  %></li> %>
        <% end %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><%= link_to 'View', user_path(current_user.id), class: "nav-link text-dark"%></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link text-dark"%></li>
            <li><%= button_to 'Signout', destroy_user_session_path, method: :delete , class: "btn"  %></li>
          </ul>
        </li>
      
        <% else %>
            <li><%= link_to 'Events', events_path, class: 'nav-link' %></li>
            <li><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
            <li><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
        <% end %>

      </ul>
    <%# </div> %>
  </div>
</nav>

app/views/home/event.html.erb
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag("index.svg", :alt => "first slide", class:"d-block w-100") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag("slide2.svg", :alt => "first slide", class:"d-block w-100") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag("slide3.svg", :alt => "first slide", class:"d-block w-100") %>

      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/index.html.erb
<h1>Active Cases</h1>

<table class="table">
  <thead>
    <tr>
      <%# <th scope="col">#</th> %>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Verified</th>
      <th scope="col">Deadline</th>
    </tr>
  </thead>
  <tbody>
  <% @cases.each do |c| %>
  <%if not c.is_closed%>
    <tr>
      <%# <th scope="row">1</th> %>
      <td><a href="/cases/<%= c.id %>"><%= c.title %></td>
      <td><%= c.description %></td>
      <% if c.is_verified%>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <%end%>
      <td><%= c.deadline %></td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
</table>